package com.collaborativeClouds.mappers;
// Generated Dec 2, 2014 11:43:13 PM by Hibernate Tools 3.6.0



/**
 * TblOnline generated by hbm2java
 */
public class TblOnline  implements java.io.Serializable {


     private String username;
     private String sessionId;

    public TblOnline() {
    }

    public TblOnline(String username, String sessionId) {
       this.username = username;
       this.sessionId = sessionId;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }




}


