package com.collaborativeClouds.mappers;
// Generated Dec 2, 2014 11:43:13 PM by Hibernate Tools 3.6.0



/**
 * TblVehicleRegistration generated by hbm2java
 */
public class TblVehicleRegistration  implements java.io.Serializable {


     private String registrationNumber;
     private String description;
     private String dealerName;
     private String dealerAddress;
     private String makerName;
     private String ownerName;
     private String ownerGuide;
     private String ownerGuideRelation;
     private String ownerPermAddress;
     private String ownerTempAddress;
     private Integer durationOfStay;
     private String panNumber;
     private String birthPlace;
     private String migratedDate;
     private String exarmyImportedVehicle;
     private String vehicleClass;
     private String vehicleIs;
     private String bodyType;
     private String vehicleType;
     private String manufactureMonth;
     private String manufactureYear;
     private int cylinders;
     private int hp;
     private int cubicCapacity;
     private String makerClassification;
     private String chassisNumber;
     private String engineNumber;
     private int seating;
     private String fuel;
     private int unladenWeight;
     private String prevRegistration;
     private String color;
     private String wheelBase;
     private TblVehicleTax tblVehicleTax;

    public TblVehicleRegistration() {
    }

	
    public TblVehicleRegistration(String registrationNumber, String description, String dealerName, String dealerAddress, String makerName, String ownerName, String ownerGuide, String ownerGuideRelation, String ownerPermAddress, String ownerTempAddress, String exarmyImportedVehicle, String vehicleClass, String vehicleIs, String bodyType, String manufactureMonth, String manufactureYear, int cylinders, int hp, int cubicCapacity, String makerClassification, String chassisNumber, String engineNumber, int seating, String fuel, int unladenWeight, String color, String wheelBase) {
        this.registrationNumber = registrationNumber;
        this.description = description;
        this.dealerName = dealerName;
        this.dealerAddress = dealerAddress;
        this.makerName = makerName;
        this.ownerName = ownerName;
        this.ownerGuide = ownerGuide;
        this.ownerGuideRelation = ownerGuideRelation;
        this.ownerPermAddress = ownerPermAddress;
        this.ownerTempAddress = ownerTempAddress;
        this.exarmyImportedVehicle = exarmyImportedVehicle;
        this.vehicleClass = vehicleClass;
        this.vehicleIs = vehicleIs;
        this.bodyType = bodyType;
        this.manufactureMonth = manufactureMonth;
        this.manufactureYear = manufactureYear;
        this.cylinders = cylinders;
        this.hp = hp;
        this.cubicCapacity = cubicCapacity;
        this.makerClassification = makerClassification;
        this.chassisNumber = chassisNumber;
        this.engineNumber = engineNumber;
        this.seating = seating;
        this.fuel = fuel;
        this.unladenWeight = unladenWeight;
        this.color = color;
        this.wheelBase = wheelBase;
    }
    public TblVehicleRegistration(String registrationNumber, String description, String dealerName, String dealerAddress, String makerName, String ownerName, String ownerGuide, String ownerGuideRelation, String ownerPermAddress, String ownerTempAddress, Integer durationOfStay, String panNumber, String birthPlace, String migratedDate, String exarmyImportedVehicle, String vehicleClass, String vehicleIs, String bodyType, String vehicleType, String manufactureMonth, String manufactureYear, int cylinders, int hp, int cubicCapacity, String makerClassification, String chassisNumber, String engineNumber, int seating, String fuel, int unladenWeight, String prevRegistration, String color, String wheelBase, TblVehicleTax tblVehicleTax) {
       this.registrationNumber = registrationNumber;
       this.description = description;
       this.dealerName = dealerName;
       this.dealerAddress = dealerAddress;
       this.makerName = makerName;
       this.ownerName = ownerName;
       this.ownerGuide = ownerGuide;
       this.ownerGuideRelation = ownerGuideRelation;
       this.ownerPermAddress = ownerPermAddress;
       this.ownerTempAddress = ownerTempAddress;
       this.durationOfStay = durationOfStay;
       this.panNumber = panNumber;
       this.birthPlace = birthPlace;
       this.migratedDate = migratedDate;
       this.exarmyImportedVehicle = exarmyImportedVehicle;
       this.vehicleClass = vehicleClass;
       this.vehicleIs = vehicleIs;
       this.bodyType = bodyType;
       this.vehicleType = vehicleType;
       this.manufactureMonth = manufactureMonth;
       this.manufactureYear = manufactureYear;
       this.cylinders = cylinders;
       this.hp = hp;
       this.cubicCapacity = cubicCapacity;
       this.makerClassification = makerClassification;
       this.chassisNumber = chassisNumber;
       this.engineNumber = engineNumber;
       this.seating = seating;
       this.fuel = fuel;
       this.unladenWeight = unladenWeight;
       this.prevRegistration = prevRegistration;
       this.color = color;
       this.wheelBase = wheelBase;
       this.tblVehicleTax = tblVehicleTax;
    }
   
    public String getRegistrationNumber() {
        return this.registrationNumber;
    }
    
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDealerName() {
        return this.dealerName;
    }
    
    public void setDealerName(String dealerName) {
        this.dealerName = dealerName;
    }
    public String getDealerAddress() {
        return this.dealerAddress;
    }
    
    public void setDealerAddress(String dealerAddress) {
        this.dealerAddress = dealerAddress;
    }
    public String getMakerName() {
        return this.makerName;
    }
    
    public void setMakerName(String makerName) {
        this.makerName = makerName;
    }
    public String getOwnerName() {
        return this.ownerName;
    }
    
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }
    public String getOwnerGuide() {
        return this.ownerGuide;
    }
    
    public void setOwnerGuide(String ownerGuide) {
        this.ownerGuide = ownerGuide;
    }
    public String getOwnerGuideRelation() {
        return this.ownerGuideRelation;
    }
    
    public void setOwnerGuideRelation(String ownerGuideRelation) {
        this.ownerGuideRelation = ownerGuideRelation;
    }
    public String getOwnerPermAddress() {
        return this.ownerPermAddress;
    }
    
    public void setOwnerPermAddress(String ownerPermAddress) {
        this.ownerPermAddress = ownerPermAddress;
    }
    public String getOwnerTempAddress() {
        return this.ownerTempAddress;
    }
    
    public void setOwnerTempAddress(String ownerTempAddress) {
        this.ownerTempAddress = ownerTempAddress;
    }
    public Integer getDurationOfStay() {
        return this.durationOfStay;
    }
    
    public void setDurationOfStay(Integer durationOfStay) {
        this.durationOfStay = durationOfStay;
    }
    public String getPanNumber() {
        return this.panNumber;
    }
    
    public void setPanNumber(String panNumber) {
        this.panNumber = panNumber;
    }
    public String getBirthPlace() {
        return this.birthPlace;
    }
    
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }
    public String getMigratedDate() {
        return this.migratedDate;
    }
    
    public void setMigratedDate(String migratedDate) {
        this.migratedDate = migratedDate;
    }
    public String getExarmyImportedVehicle() {
        return this.exarmyImportedVehicle;
    }
    
    public void setExarmyImportedVehicle(String exarmyImportedVehicle) {
        this.exarmyImportedVehicle = exarmyImportedVehicle;
    }
    public String getVehicleClass() {
        return this.vehicleClass;
    }
    
    public void setVehicleClass(String vehicleClass) {
        this.vehicleClass = vehicleClass;
    }
    public String getVehicleIs() {
        return this.vehicleIs;
    }
    
    public void setVehicleIs(String vehicleIs) {
        this.vehicleIs = vehicleIs;
    }
    public String getBodyType() {
        return this.bodyType;
    }
    
    public void setBodyType(String bodyType) {
        this.bodyType = bodyType;
    }
    public String getVehicleType() {
        return this.vehicleType;
    }
    
    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType;
    }
    public String getManufactureMonth() {
        return this.manufactureMonth;
    }
    
    public void setManufactureMonth(String manufactureMonth) {
        this.manufactureMonth = manufactureMonth;
    }
    public String getManufactureYear() {
        return this.manufactureYear;
    }
    
    public void setManufactureYear(String manufactureYear) {
        this.manufactureYear = manufactureYear;
    }
    public int getCylinders() {
        return this.cylinders;
    }
    
    public void setCylinders(int cylinders) {
        this.cylinders = cylinders;
    }
    public int getHp() {
        return this.hp;
    }
    
    public void setHp(int hp) {
        this.hp = hp;
    }
    public int getCubicCapacity() {
        return this.cubicCapacity;
    }
    
    public void setCubicCapacity(int cubicCapacity) {
        this.cubicCapacity = cubicCapacity;
    }
    public String getMakerClassification() {
        return this.makerClassification;
    }
    
    public void setMakerClassification(String makerClassification) {
        this.makerClassification = makerClassification;
    }
    public String getChassisNumber() {
        return this.chassisNumber;
    }
    
    public void setChassisNumber(String chassisNumber) {
        this.chassisNumber = chassisNumber;
    }
    public String getEngineNumber() {
        return this.engineNumber;
    }
    
    public void setEngineNumber(String engineNumber) {
        this.engineNumber = engineNumber;
    }
    public int getSeating() {
        return this.seating;
    }
    
    public void setSeating(int seating) {
        this.seating = seating;
    }
    public String getFuel() {
        return this.fuel;
    }
    
    public void setFuel(String fuel) {
        this.fuel = fuel;
    }
    public int getUnladenWeight() {
        return this.unladenWeight;
    }
    
    public void setUnladenWeight(int unladenWeight) {
        this.unladenWeight = unladenWeight;
    }
    public String getPrevRegistration() {
        return this.prevRegistration;
    }
    
    public void setPrevRegistration(String prevRegistration) {
        this.prevRegistration = prevRegistration;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getWheelBase() {
        return this.wheelBase;
    }
    
    public void setWheelBase(String wheelBase) {
        this.wheelBase = wheelBase;
    }
    public TblVehicleTax getTblVehicleTax() {
        return this.tblVehicleTax;
    }
    
    public void setTblVehicleTax(TblVehicleTax tblVehicleTax) {
        this.tblVehicleTax = tblVehicleTax;
    }




}


