package com.collaborativeClouds.mappers;
// Generated Dec 2, 2014 11:43:13 PM by Hibernate Tools 3.6.0



/**
 * TblVehicleTax generated by hbm2java
 */
public class TblVehicleTax  implements java.io.Serializable {


     private String registrationNumber;
     private TblVehicleRegistration tblVehicleRegistration;
     private String taxLicenceNumber;
     private int paidAmount;
     private String amountPaidOn;
     private String paidFrom;
     private String paidTo;
     private int cessAmount;
     private String cessDate;
     private String dateOfDelivery;
     private String dateOfRegistration;
     private String registrationValidityFrom;
     private String registrationValidityTo;

    public TblVehicleTax() {
    }

    public TblVehicleTax(TblVehicleRegistration tblVehicleRegistration, String taxLicenceNumber, int paidAmount, String amountPaidOn, String paidFrom, String paidTo, int cessAmount, String cessDate, String dateOfDelivery, String dateOfRegistration, String registrationValidityFrom, String registrationValidityTo) {
       this.tblVehicleRegistration = tblVehicleRegistration;
       this.taxLicenceNumber = taxLicenceNumber;
       this.paidAmount = paidAmount;
       this.amountPaidOn = amountPaidOn;
       this.paidFrom = paidFrom;
       this.paidTo = paidTo;
       this.cessAmount = cessAmount;
       this.cessDate = cessDate;
       this.dateOfDelivery = dateOfDelivery;
       this.dateOfRegistration = dateOfRegistration;
       this.registrationValidityFrom = registrationValidityFrom;
       this.registrationValidityTo = registrationValidityTo;
    }
   
    public String getRegistrationNumber() {
        return this.registrationNumber;
    }
    
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }
    public TblVehicleRegistration getTblVehicleRegistration() {
        return this.tblVehicleRegistration;
    }
    
    public void setTblVehicleRegistration(TblVehicleRegistration tblVehicleRegistration) {
        this.tblVehicleRegistration = tblVehicleRegistration;
    }
    public String getTaxLicenceNumber() {
        return this.taxLicenceNumber;
    }
    
    public void setTaxLicenceNumber(String taxLicenceNumber) {
        this.taxLicenceNumber = taxLicenceNumber;
    }
    public int getPaidAmount() {
        return this.paidAmount;
    }
    
    public void setPaidAmount(int paidAmount) {
        this.paidAmount = paidAmount;
    }
    public String getAmountPaidOn() {
        return this.amountPaidOn;
    }
    
    public void setAmountPaidOn(String amountPaidOn) {
        this.amountPaidOn = amountPaidOn;
    }
    public String getPaidFrom() {
        return this.paidFrom;
    }
    
    public void setPaidFrom(String paidFrom) {
        this.paidFrom = paidFrom;
    }
    public String getPaidTo() {
        return this.paidTo;
    }
    
    public void setPaidTo(String paidTo) {
        this.paidTo = paidTo;
    }
    public int getCessAmount() {
        return this.cessAmount;
    }
    
    public void setCessAmount(int cessAmount) {
        this.cessAmount = cessAmount;
    }
    public String getCessDate() {
        return this.cessDate;
    }
    
    public void setCessDate(String cessDate) {
        this.cessDate = cessDate;
    }
    public String getDateOfDelivery() {
        return this.dateOfDelivery;
    }
    
    public void setDateOfDelivery(String dateOfDelivery) {
        this.dateOfDelivery = dateOfDelivery;
    }
    public String getDateOfRegistration() {
        return this.dateOfRegistration;
    }
    
    public void setDateOfRegistration(String dateOfRegistration) {
        this.dateOfRegistration = dateOfRegistration;
    }
    public String getRegistrationValidityFrom() {
        return this.registrationValidityFrom;
    }
    
    public void setRegistrationValidityFrom(String registrationValidityFrom) {
        this.registrationValidityFrom = registrationValidityFrom;
    }
    public String getRegistrationValidityTo() {
        return this.registrationValidityTo;
    }
    
    public void setRegistrationValidityTo(String registrationValidityTo) {
        this.registrationValidityTo = registrationValidityTo;
    }




}


