package com.collaborativeClouds.mappers;
// Generated Dec 2, 2014 11:43:13 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TblVehiclePollution generated by hbm2java
 */
public class TblVehiclePollution  implements java.io.Serializable {


     private Integer id;
     private String registrationNumber;
     private Date dateOfTesting;
     private String serialNo;
     private String timeOfTesting;
     private int speedometerReading;
     private Date validUpto;
     private String certificateImagePath;
     private String issuedBy;
     private String issuerAddress;

    public TblVehiclePollution() {
    }

    public TblVehiclePollution(String registrationNumber, Date dateOfTesting, String serialNo, String timeOfTesting, int speedometerReading, Date validUpto, String certificateImagePath, String issuedBy, String issuerAddress) {
       this.registrationNumber = registrationNumber;
       this.dateOfTesting = dateOfTesting;
       this.serialNo = serialNo;
       this.timeOfTesting = timeOfTesting;
       this.speedometerReading = speedometerReading;
       this.validUpto = validUpto;
       this.certificateImagePath = certificateImagePath;
       this.issuedBy = issuedBy;
       this.issuerAddress = issuerAddress;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRegistrationNumber() {
        return this.registrationNumber;
    }
    
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }
    public Date getDateOfTesting() {
        return this.dateOfTesting;
    }
    
    public void setDateOfTesting(Date dateOfTesting) {
        this.dateOfTesting = dateOfTesting;
    }
    public String getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }
    public String getTimeOfTesting() {
        return this.timeOfTesting;
    }
    
    public void setTimeOfTesting(String timeOfTesting) {
        this.timeOfTesting = timeOfTesting;
    }
    public int getSpeedometerReading() {
        return this.speedometerReading;
    }
    
    public void setSpeedometerReading(int speedometerReading) {
        this.speedometerReading = speedometerReading;
    }
    public Date getValidUpto() {
        return this.validUpto;
    }
    
    public void setValidUpto(Date validUpto) {
        this.validUpto = validUpto;
    }
    public String getCertificateImagePath() {
        return this.certificateImagePath;
    }
    
    public void setCertificateImagePath(String certificateImagePath) {
        this.certificateImagePath = certificateImagePath;
    }
    public String getIssuedBy() {
        return this.issuedBy;
    }
    
    public void setIssuedBy(String issuedBy) {
        this.issuedBy = issuedBy;
    }
    public String getIssuerAddress() {
        return this.issuerAddress;
    }
    
    public void setIssuerAddress(String issuerAddress) {
        this.issuerAddress = issuerAddress;
    }




}


